### ISSUE TITLE
exoflex: custom fonts won't load in Button

### ISSUE THREAD

**Issue by cindmichelle** [kodefox/infra#493]
**Describe the bug**
custom fonts won't load only on `Button` component. I also have tried to add props `textPreset` according to the docs, but the fonts still won't load.

my code according to the custom theme looks like this : 
```
const THEMES: Theme = {
  ...DefaultTheme,
  fonts: {
    default: {
      ...DefaultTheme.fonts.default,
      normal: {
        name: 'Roboto-Regular',
        weight: '400',
        source: RobotoRegular,
      },
      bold: {
        name: 'Roboto-Bold',
        weight: '700',
        source: RobotoBold,
      },
    },
  },
};
```

**To Reproduce**
To reproduce the behavior:
1. Add custom fonts to `ThemeProvider`.
2. Add `Button`
3. Running it Simulator

**Expected behavior**
Custom fonts should be loaded on 'Button'.

**Screenshots**
![image](https://user-images.githubusercontent.com/46435998/81784363-f29ea300-9526-11ea-866d-538cc0b38b65.png)

**Smartphone (please complete the following information):**
 - Device:  iPhone6
 - OS: iOS12.1
 - Package version v3.3.1

**Comment by oshimayoan** [comment]
@cindmichelle Actually, your font is loaded but not used by the button. The reason why your font is not used is that exoflex button was designed to use the font-weight `500` for the label. And it appears that your project doesn't provide the custom font with that weight at all.

Previously, exoflex doesn't give you the ability to change the font-weight of the button's label. But now we support it since version `3.4.0`, which we just release just now.

To make the button use your custom font, you can change the font-weight through the theme style.

```tsx
const THEMES: Partial<Theme> = {
  fonts: {
    default: {
      ...DefaultTheme.fonts.default,
      normal: {
        name: 'Roboto-Regular',
        weight: '400',
        source: RobotoRegular,
      },
      bold: {
        name: 'Roboto-Bold',
        weight: '700',
        source: RobotoBold,
      },
    },
  },
  style: {
    button: {
      labelFontWeight: '400',
    },
  },
}
```

You can change that to `700` if you want to use your bold font. Also, you can change the font to italic by using `labelFontStyle: 'italic'`.
